version: '3.8'

services:
  ml:
    build:
      context: ./ml
    ports:
      - "4000:4000"

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - VITE_SERVER_ENDPOINT=/api
      - VITE_ML_ENDPOINT=/ml

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - server_data:/app/public
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27018/pekanu
      - JWT_SECRET=iitb_affect_aware
      - JWT_EXPIRY=7d
      - ADMIN_USERNAME=admin

  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  server_data:
