version: '3.8'

services:
  ml:
    build:
      context: ./ml
    ports:
      - '4000:4000'

  client:
    build:
      context: ./client
      args:
        - VITE_SERVER_ENDPOINT=
        - VITE_ML_ENDPOINT=
    ports:
      - '3000:3000'

  server:
    build:
      context: ./server
    ports:
      - '5000:5000'
    volumes:
      - server_data:/app/public
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/pekanu
      - JWT_SECRET=iitb_affect_aware
      - JWT_EXPIRY=7d
      - ADMIN_USERNAME=admin
    links:
      - mongo

  mongo:
    image: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: pekanu
      ME_CONFIG_MONGODB_ADMINPASSWORD: iitb_affect_aware
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - server
      - ml

volumes:
  mongodb_data:
  server_data:
